### ISSUE TITLE
new assignment on sift and kd tree based  feature matching

### ISSUE THREAD

**Issue by xiahaa** [xiaohanlyu/image-stitching#11]
https://github.com/xiaohanlyu/image-stitching/blob/master/docs/EX5.pdf
read this and try to do this assignment which should be very easy.

**Comment by hannaLyu** [comment]
until now i done some sift and i already upload it, but it seems incorrect. Maybe some bug in my plot code but i cannot come up with it.

**Comment by xiahaa** [comment]
check [my correction](https://github.com/xiaohanlyu/image-stitching/commit/e9a1aeab7af5405b238aeb0e35e04abecccc2d7f)

plot error.

check my answer.
In fact, the aim is to let you implement the maching yourself rather than call the sift_matching function.....
But it is ok.
