### ISSUE TITLE
RANSAC for line and plane estimation.

### ISSUE THREAD

**Issue by xiahaa** [xiaohanlyu/image-stitching#13]
[document](https://github.com/xiaohanlyu/image-stitching/blob/master/docs/ex6.pdf)

**Comment by xiahaa** [comment]
@xiaohanlyu 

use the code in `main_ransac.m` to generate data and try with your RANSAC implementation.
```
clc;close all;clear all;

addpath(genpath('./'));

%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% either load or call gen_line_data()
% load ../data/LineData
% X = gen_line_data(500);

% for plane
[X,Xi,Xo] = gen_plane_data(200);

ph = tohomogeneous(X);

%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Results Visualization
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plot_plane_case(X,result,Xi,Xo);

```

**Comment by xiahaa** [comment]
@xiaohanlyu 
sorry you need to implement this `tohomogeneous` function.

**Comment by hannaLyu** [comment]
I upload a unfinished file. cause the result seems like a line but i think it isn't my want. Maybe the problem is in the distance code? 
Also, its still unclear for me in nullspace. i know the definition and how to calculate it. but i don't know the physical meaning and we can use it to do what. So do you have some reading material which suggest for me?

**Comment by xiahaa** [comment]
@xiaohanlyu 
```
for i=1:iter
   idx = randperm(number,2);
   sample = X(:,idx); 
   x = sample(:, 1);
   y = sample(:, 2);
   %coordinates of two points
   p1=[x(1);y(1);1];
   p2=[x(2);y(2);1];
   %line which two points decided
   line=cross(p1,p2); 
   line=transpose(line);
   %caculate distance between every point and current line  
   distance=abs(line(1:2)*(X - repmat(sample(:,1),1,number)));%%%%???????????????
   inlierIdx = find(distance<sigma);%find inlier which colse to line
   inlierNum = length(inlierIdx);  %caculate inlier'number
   if inlierNum>pretotal           
         pretotal=inlierNum;
         bestline=line;        
    end  
 end
```
point 2 line distance = abs(ax+by+c)/sqrt(a^2+b^2)
so what you should do is like
line' * x ./ sqrt(line(1)^2+line(2)^2)

From your implementation, I have no idea what you plan to do.......

For nullspace, check [wikipedia](https://zh.wikipedia.org/wiki/%E9%9B%B6%E7%A9%BA%E9%97%B4) and the linear algenbra I uploaded.

Regard what you can do with Nullspace, the short answer is 
I think you know that if you have an equation like Ax=b, b neq 0, then x can be solved in the least square sense by using the so called pseudo-inverse of A like x = (A^TA)^(-1)*A^Tb.

However, imaging now you have an equation like Ax=0, you would like to find a solution of x. This time, you cannot use least square solution since you will get the trivial solution x=0. What should you do?
Now you need the nullspace and null vector because they can give you the solution of x. I think right now you can simply memorize this as follows

> whenever I need to solve an equation like Ax=0, I need to compute the null vector of A.

It really depends on your future plan wether or not to understand this deeply. For example, if you will work with IC design, then maths are not very important. If you would like to work with control theory, the quadratic optimization may be more important. If you would like to work with computer vision, image analysis, machine learning, then you need this and you will soon or not meet this nullspace and null vector again.

**Comment by hannaLyu** [comment]
Now i have questions about plot function. what' s the meaning of the input 'result'? is it symbol on inlier? 
there is 'result.params' in function, what's parameter is it? the point's id? is that means if i want use this function, the result must include inlier and parameter?

**Comment by xiahaa** [comment]
@xiaohanlyu 
My mistake:
result.inliers: logical array indicating the corresponding point is inlier or not. for example: you have 100 points, then result.inliers is a array of 100x1. If the i element is 1, then point i is an inlier.

result.params: model parameters. For example, for line fitting, result.params = [a,b,c].
For plane, result.params = [a,b,c,d]

**Comment by hannaLyu** [comment]
It seems line is correct but inlier is wrong. But i think if line is correct so inlier actually is correct. The problem is in plot part. But i check so many times and can't find mistake.

**Comment by xiahaa** [comment]
> It seems line is correct but inlier is wrong. But i think if line is correct so inlier actually is correct. The problem is in plot part. But i check so many times and can't find mistake.

no, you make a bug.

```
for i=1:iter
   idx = randperm(number,2);
   sample = X(:,idx); 
   x = sample(:, 1);
   y = sample(:, 2);

    %coordinates of two points
   p1=[x(1);y(1);1];
   p2=[x(2);y(2);1];
    %line which two points decided
   line=cross(p1,p2); 
   line=transpose(line);
  distance=abs(line * [X;ones(1,size(X,2))] )./ sqrt(line(1)^2+line(2)^2);
    inlierIdx = find(distance<sigma);%find inlier which colse to line
    inlierNum = length(inlierIdx);  %caculate inlier'number
     if inlierNum>pretotal         %find best line  
         pretotal=inlierNum;
         bestdistance = distance;
         bestline=line;        
    end  
end


result=distance<sigma;
linepara=bestline;
end
```

If you do like this, then the bestline is the best line you found. However, distance is the distance of last iteration. That's why they cannot match.

**Comment by hannaLyu** [comment]
I just use a simple way cause i cannot find the function to calculate plane function in homogeneous coordinates case.

**Comment by xiahaa** [comment]
@xiaohanlyu 
check my answer.
[`line_estimation`](https://github.com/xiaohanlyu/image-stitching/blob/master/src/common/line_estimation.m) *using homogeneous coordinate and nullspace*
[`plane_estimation`](https://github.com/xiaohanlyu/image-stitching/blob/master/src/common/plane_estimation.m) *using homogeneous coordinate and nullspace*
[`fromhomogeneous`](https://github.com/xiaohanlyu/image-stitching/blob/master/src/precompute/fromhomogeneous.m) *from homogeneous to inhomogeneous*
[`tohomogeneous`](https://github.com/xiaohanlyu/image-stitching/blob/master/src/precompute/tohomogeneous.m) *from inhomogeneous to homogeneous*
[`main_ransac`](https://github.com/xiaohanlyu/image-stitching/blob/master/src/main_ransac.m) how to use structure in Matlab and how to use function handler.

several comments:
1. learn how to organize your code;
2. learn how to use homogeneous coordinate.

**Comment by xiahaa** [comment]
> nction in homogene

[a b c d][x y z 1]^T = 0 ----> [x y z 1][a b c d]^T=0 ----->
[a1 b1 c1 d1;
 a2 b2 c2 d2;
   .    .   .    .  ;
   .    .   .    .  ;
 an bn cn dn][a b c d]^T=0 ------->
Ax = 0 ------> 
x = null(A)
