### ISSUE TITLE
non-maximum suppression

### ISSUE THREAD

**Issue by hannaLyu** [xiaohanlyu/image-stitching#6]
I uploaded new files in src. The results seems worse than before. I want to know if my code of non-maximum is wrong or i need to try to find more optimal parameter?

**Comment by xiahaa** [comment]
i cannot see your code.
please make a commit?

**Comment by xiahaa** [comment]
so you push a new branch, OK

**Comment by xiahaa** [comment]
@xiaohanlyu 
I give you a sample code in your new branch. see and try.

**Comment by xiahaa** [comment]
@xiaohanlyu 
A small bug on gaussian filter.
You generated a horizontal template, I think you want to do a nxn template. But you used h.*h.....

This week, I think we can not only talk about blob features, but also feature descriptor and feature matching.

**Comment by xiahaa** [comment]
@xiaohanlyu 
I have merged your branch,
I have added my modification of your code.
Check the new result.
